services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=n8n.orfel.de
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.orfel.de/
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
    expose:
      - "5678"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/n8n/data:/home/node/.n8n
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
