services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.orfel.de
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.orfel.de
      - APACHE_DISABLE_REWRITE_IP=1
    expose:
      - "80"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/nextcloud/html:/var/www/html
      - /mnt/Jannik-Cloud-Volume-01/nextcloud/data:/var/www/html/data
    networks:
      - jannik-cloud-net
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis

  nextcloud-mariadb:
    image: mariadb:11
    container_name: nextcloud-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/nextcloud/mysql:/var/lib/mysql
    networks:
      - jannik-cloud-net

  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/nextcloud/redis:/data
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
